name: ba-ex

channels:
  - esri
  - conda-forge

dependencies:
  - jupyterlab
  - matplotlib
  - nodejs
  - pip
  - pytest
  - python=3.7
  - python-dotenv
  - pyarrow
  - pyyaml
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tox
  - pip:
    - azure-storage-blob
    - boto3
    - bump2version
    - ipykernel
    - nbsphinx
    - sphinx
    - sphinx-autodoc-typehints
    - twine
