name: ba-examples

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - featuretools
  - jupyterlab
  - matplotlib
  - nodejs
  - pip
  - pytest
  - python=3.9
  - python-dotenv
#  - pyarrow
  - pyyaml
  - scipy
  - scikit-learn
  - seaborn
#  - shapely
  - swifter
  - tox
  - pip:
    - boto3
    - bump2version
    - ipykernel
    - nbsphinx
    - sodapy
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
